# Generated by Django 4.2.7 on 2023-11-13 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ProductivityApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coordinator",
            name="total_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
