# Generated by Django 4.2.7 on 2023-11-15 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductivityApp', '0003_alter_week_coordinator'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
            ],
        ),
    ]
