# Generated by Django 4.2.7 on 2023-11-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProductivityApp', '0004_currentweek'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentweek',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
