# Generated by Django 4.2.7 on 2023-11-16 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ProductivityApp", "0002_alter_coordinator_total_cost"),
        ("ProductivityApp", "0006_remove_coordinator_lines_completed_and_more"),
    ]

    operations = []
