# Generated by Django 4.2.7 on 2023-11-23 17:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ProductivityApp', '0007_merge_20231116_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentweek',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
